# Site settings
title: "SYCMR Technical LLC"
description: "SYCMR Technical LLC - WIP Website"
url: "https://www.sycmr.com" # Replace with your site's URL
baseurl: "" # Leave empty if your site is at the root, otherwise specify a path (e.g., /blog)

# Minima theme settings
theme: minima

# Header image settings
header:
  image: "/docs/assets/images/SYCMR_Logo_word_Clearance_cropped.jpg"  # Path to the first title image in the root directory
  #image_alt: "Image 001 as the header"
  #image2: "/image002.jpg"  # Path to the second title image in the root directory
  #image2_alt: "Image 002 as the header"

# Navigation links
navbar:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Blog"
    url: "/blog"
  - title: "Contact"
    url: "/contact"

# Enable Markdown features
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed

# Build settings
exclude:
  - README.md
  - LICENSE.txt
